# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=yyyyyy.us-east-1.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='XXXXXXXXXXXX' password='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
sasl.mechanism=PLAIN
# Required for correctness in Apache Kafka clients prior to 2.6
client.dns.lookup=use_all_dns_ips
 
# Best practice for higher availability in Apache Kafka clients prior to 3.0
session.timeout.ms=45000
 
# Best practice for Kafka producer to prevent data loss
acks=all
 
client.id=ccloud-java-client-57fca95e-0f41-4e10-80a3-XXXXXXXXXX

group.id=consumer-id

group.id=consumer-id

# Kafkorama Gateway parameter
topics=u

# Kafkorama Gateway parameter
#topics.regex=server


# Kafkorama Gateway parameter
# options `yes` or `no`
# yes -> At start each node will try to recover messages from kafka cluster. The consumer will consume all the messages published in the last time value set with parameter `CacheExpireTime`.
#        The default value is 180 seconds (3 minutes). To change the value add the parameter `CacheExpireTime` in `kafkorama-gateway.conf` file.
# no  -> The consumer starts from last offset found in kafka.
recovery.on.start=no

# Kafkorama Gateway parameter
# Set the number of consumers used by the node to consume messages from kafka cluster.
consumers.size=1
